//********************************************************************************
//*  Copyright: National ICT Australia,  2007 - 2010                             *
//*  Developed at the ATP lab, Networked Systems research theme                  *
//*  Author(s): Yuriy Tselishchev                                                *
//*  This file is distributed under the terms in the attached LICENSE file.      *
//*  If you do not find this file, copies can be found by writing to:            *
//*                                                                              *
//*      NICTA, Locked Bag 9013, Alexandria, NSW 1435, Australia                 *
//*      Attention:  License Inquiry.                                            *
//*                                                                              *
//*******************************************************************************/

//********************************************************************************
//*  Modified for GreenCastalia integration					 *
//*  Modification date: 07/01/2013                                               *
//********************************************************************************
//*  Copyright (C): Dora Spenza, David Benedetti, 2013                           *
//*  Author(s): Dora Spenza, David Benedetti                                     *
//*  Developed at Computer Science Department, Sapienza University of Rome       *
//*  This file is distributed under the terms in the attached LICENSE_GC file.   *
//*******************************************************************************/

message ResourceManagerMessage {
	double powerConsumed;
}

message ResourceManagerHarvestingMessage {
	double harvestingPower;
}
