//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/eamultipathRingsRouting/EAmultipathRingsRoutingControl.msg.
//

#ifndef _EAMULTIPATHRINGSROUTINGCONTROL_M_H_
#define _EAMULTIPATHRINGSROUTINGCONTROL_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>src/node/communication/routing/eamultipathRingsRouting/EAmultipathRingsRoutingControl.msg:13</tt> by nedtool.
 * <pre>
 * enum eamultipathRingsRoutingControlDef
 * {
 * 
 *     MPRINGS_NOT_CONNECTED = 1;
 *     MPRINGS_CONNECTED_TO_TREE = 2;
 *     MPRINGS_TREE_LEVEL_UPDATED = 3;
 * }
 * </pre>
 */
enum eamultipathRingsRoutingControlDef {
    MPRINGS_NOT_CONNECTED = 1,
    MPRINGS_CONNECTED_TO_TREE = 2,
    MPRINGS_TREE_LEVEL_UPDATED = 3
};

/**
 * Class generated from <tt>src/node/communication/routing/eamultipathRingsRouting/EAmultipathRingsRoutingControl.msg:19</tt> by nedtool.
 * <pre>
 * message EAmultipathRingsRoutingControlMessage
 * {
 *     int eamultipathRingsRoutingControlMessageKind @enum(eamultipathRingsRoutingControlDef);
 *     int sinkID;
 *     int level;
 * }
 * </pre>
 */
class EAmultipathRingsRoutingControlMessage : public ::cMessage
{
  protected:
    int eamultipathRingsRoutingControlMessageKind_var;
    int sinkID_var;
    int level_var;

  private:
    void copy(const EAmultipathRingsRoutingControlMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EAmultipathRingsRoutingControlMessage&);

  public:
    EAmultipathRingsRoutingControlMessage(const char *name=NULL, int kind=0);
    EAmultipathRingsRoutingControlMessage(const EAmultipathRingsRoutingControlMessage& other);
    virtual ~EAmultipathRingsRoutingControlMessage();
    EAmultipathRingsRoutingControlMessage& operator=(const EAmultipathRingsRoutingControlMessage& other);
    virtual EAmultipathRingsRoutingControlMessage *dup() const {return new EAmultipathRingsRoutingControlMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getEamultipathRingsRoutingControlMessageKind() const;
    virtual void setEamultipathRingsRoutingControlMessageKind(int eamultipathRingsRoutingControlMessageKind);
    virtual int getSinkID() const;
    virtual void setSinkID(int sinkID);
    virtual int getLevel() const;
    virtual void setLevel(int level);
};

inline void doPacking(cCommBuffer *b, EAmultipathRingsRoutingControlMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, EAmultipathRingsRoutingControlMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef _EAMULTIPATHRINGSROUTINGCONTROL_M_H_

